default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: thuy2495
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: dangki1
  
# test:
#   <<: *default
#   database: login_app_test
  
production:
  <<: *default
  database: dangki1
  username: dangki1
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>



